apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tdvnl5q3y-nodejs
  janus-idp.io/tekton: tdvnl5q3y-nodejs
  backstage.io/kubernetes-id: tdvnl5q3y-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tdvnl5q3y-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
